import type { HelpState } from "@marvin-toolkit/mcp-shared/contracts";

/**
 * A representative full HelpState (ADR-0024) shared by the tests and the story —
 * the `telegram-publications` project from the approved mockup: every command
 * group and all 57 commands, a mix of lit/dim MCP servers, and a non-trivial
 * artifact count. All values are fixed literals (no Date.now()) so the story and
 * snapshots stay deterministic. `[group, name, blurb, human]` tuples keep the
 * 57-command reference readable without losing coverage.
 */
const COMMANDS: Array<[string, string, string, boolean]> = [
  ["core", "commit", "Conventional commit, kanban-linked", false],
  ["core", "debug", "Systematic root-cause debugging", false],
  ["core", "adr", "Create an Architecture Decision Record", false],
  ["core", "changelog", "Changelog from git history", false],
  ["core", "readme", "Generate or update README", false],
  ["core", "migration-plan", "Plan a migration or major refactor", false],
  ["core", "explain", "Explain code, logic, and design", false],
  ["core", "docs-search", "Search project documentation", false],
  ["core", "handoff", "Capture a session handoff", false],
  ["core", "handoff-list", "List handoff documents", false],
  ["core", "lessons", "Team lessons-learned store", false],
  ["core", "help", "This dashboard + command index", false],
  ["core", "dashboard", "Whole-toolbox state report", false],
  ["adr", "adr-review", "Review a proposed ADR", false],
  ["adr", "adr-accept", "Ratify an ADR (human-run)", true],
  ["adr", "adr-audit", "Lint the whole ADR corpus", false],
  ["adr", "adr-coverage", "Find undocumented decisions", false],
  ["adr", "adr-supersede", "Roll back an accepted ADR (human-run)", true],
  ["adr", "adr-sync", "Refresh the ADR digest in CLAUDE.md (human-run)", true],
  ["pr", "pr-create", "Open a pull request", false],
  ["pr", "pr-review", "Review a PR on GitHub", false],
  ["pr", "pr-resolve", "Address PR review threads", false],
  ["pr", "pr-merge", "Merge a PR, then sync the base", false],
  ["task", "task-start", "Spec out a task (Phase 1)", false],
  ["task", "task-implement", "Implement a ready spec", false],
  ["task", "task-verify", "Run the project quality gates", false],
  ["task", "task-deliver", "Commit and open a PR", false],
  ["task", "task-summary", "Delivery digest for a task", false],
  ["sec", "sec-scan", "Full OWASP Top-10 audit", false],
  ["sec", "sec-secrets", "Scan for leaked secrets", false],
  ["sec", "sec-deps", "Dependency CVE / license audit", false],
  ["sec", "sec-gate", "Fast pre-commit security gate", false],
  ["sec", "sec-threat-model", "STRIDE threat model", false],
  ["sec", "sec-iac", "Infrastructure-as-Code review", false],
  ["sec", "sec-ci", "CI/CD pipeline audit", false],
  ["sec", "sec-fix", "Patch a vulnerability with tests", false],
  ["sec", "sec-compliance", "OWASP ASVS gap analysis", false],
  ["sec", "sec-pentest", "Tailored pentest checklist", false],
  ["sec", "sec-report", "List saved security reports", false],
  ["refactor", "refactor-audit", "Structural audit + hotspots", false],
  ["refactor", "refactor-smells", "Scoped code-smell scan", false],
  ["refactor", "refactor-plan", "Sequence findings into steps", false],
  ["refactor", "refactor-apply", "Apply one refactor step, gated", false],
  ["kanban", "kanban-menu", "Board action menu", false],
  ["kanban", "kanban-bug", "New bug task", false],
  ["kanban", "kanban-feature", "New feature task", false],
  ["kanban", "kanban-chore", "New chore task", false],
  ["kanban", "kanban-spike", "New spike task", false],
  ["kanban", "kanban-start", "Move a task to in-progress", false],
  ["kanban", "kanban-review", "Move a task to review", false],
  ["kanban", "kanban-done", "Move a task to done", false],
  ["kanban", "kanban-list", "List board tasks", false],
  ["kanban", "kanban-show", "Show one task", false],
  ["kanban", "kanban-tracker", "Link a tracker URL", false],
  ["kanban", "kanban-status", "Set a task status", false],
  ["kanban", "kanban-config", "Show or edit board config", false],
  ["kanban", "kanban-help", "Board help", false],
];

export const helpFixture: HelpState = {
  version: "0.1.0",
  slogan: "Claude Code toolset for AI development without panic",
  project: "telegram-publications",
  git: {
    branch: "task/telegram-publications-ingestion",
    base_branch: "main",
    has_git: true,
    has_gh: true,
  },
  statuses: [
    { key: "todo", role: "todo", count: 0 },
    { key: "wip", role: "wip", count: 0 },
    { key: "review", role: "review", count: 0 },
    { key: "done", role: "done", count: 0 },
    { key: "blocked", role: "blocked", count: 0 },
  ],
  artifacts: { specs: 40, handoffs: 0, audits: 0, lessons: 0 },
  servers: [
    { name: "marvin", enabled: true },
    { name: "context7", enabled: true },
    { name: "gitmcp", enabled: true },
    { name: "playwright", enabled: false },
    { name: "telegram", enabled: true },
    { name: "postgres", enabled: true },
    { name: "github", enabled: true },
    { name: "sentry", enabled: false },
    { name: "filesystem", enabled: true },
    { name: "obsidian", enabled: false },
    { name: "chrome-devtools", enabled: true },
    { name: "fetch", enabled: false },
  ],
  groups: [
    { group: "core", blurb: "Everyday dev — commits, debugging, docs, ADRs, handoffs" },
    { group: "adr", blurb: "Architecture Decision Record lifecycle" },
    { group: "pr", blurb: "Pull-request lifecycle — create, review, resolve, merge" },
    { group: "task", blurb: "Spec-driven pipeline — start, implement, verify, deliver" },
    { group: "sec", blurb: "Security scanners — secrets, deps, threat models & more" },
    { group: "refactor", blurb: "Code-health — audit, smells, plan, apply" },
    { group: "kanban", blurb: "Lightweight board tracker — create, move, list, configure" },
  ],
  commands: COMMANDS.map(([group, name, blurb, human]) => ({ group, name, blurb, human })),
};
