// Importable backend for mn.eject. Pure logic, no CLI bootstrap.
//
// Adapter-driven since PR-2: orchestration knows nothing about destination
// paths or content rendering — it asks the supplied `adapter` for both.
// `claudeAdapter` is the default; PR-3 adds a Codex adapter alongside it.
//
// Layout: this is the canonical copy. `cli/src/lib/eject-core.mjs` is a
// byte-identical synced copy generated by `cli/scripts/sync-core.mjs` and
// CI-guarded against drift. Both the in-skill `eject.mjs` wrapper (Claude
// Code) and the `marvin` CLI import from here.

import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";

export const KNOWN_PACKS = new Set([
  "marvin-core-pack",
  "marvin-security-pack",
  "marvin-taskmaster-pack",
]);
export const KIND_DIRS = { skill: "skills", command: "commands", agent: "agents" };
export const VALID_KINDS = new Set(["skills", "commands", "agents"]);
export const HEADER_PREFIX = "<!-- marvin-eject: source=";

// ─── arg parsing ────────────────────────────────────────────────────────────

export function parseArgs(argv) {
  const out = { target: null, only: null, apply: false, source: null, help: false };
  const positional = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--apply") out.apply = true;
    else if (arg === "--help" || arg === "-h") out.help = true;
    else if (arg === "--only") out.only = argv[++i] ?? null;
    else if (arg.startsWith("--only=")) out.only = arg.slice("--only=".length);
    else if (arg === "--source") out.source = argv[++i] ?? null;
    else if (arg.startsWith("--source=")) out.source = arg.slice("--source=".length);
    else if (arg.startsWith("--")) throw new ValidationError(`unknown flag: ${arg}`);
    else positional.push(arg);
  }
  if (positional.length > 1) throw new ValidationError(`unexpected extra arguments: ${positional.slice(1).join(" ")}`);
  out.target = positional[0] ?? null;
  if (out.only !== null) {
    const kinds = out.only.split(",").map((s) => s.trim()).filter(Boolean);
    for (const k of kinds) {
      if (!VALID_KINDS.has(k)) throw new ValidationError(`--only kind must be one of skills,commands,agents (got "${k}")`);
    }
    out.only = kinds;
  }
  return out;
}

export class ValidationError extends Error { constructor(msg) { super(msg); this.name = "ValidationError"; } }

// ─── target parsing ─────────────────────────────────────────────────────────

export function parseTarget(target) {
  if (!target) throw new ValidationError("target is required");
  const parts = target.split("/");
  const pack = parts[0];
  if (!KNOWN_PACKS.has(pack)) {
    throw new ValidationError(
      `unknown pack "${pack}". Must be one of: ${[...KNOWN_PACKS].join(", ")}`
    );
  }
  if (parts.length === 1) return { pack, kind: null, name: null };
  if (parts.length !== 3) throw new ValidationError(`malformed target: "${target}". Expected "<pack>" or "<pack>/<kind>/<name>"`);
  const kindPlural = parts[1];
  if (!VALID_KINDS.has(kindPlural)) throw new ValidationError(`unknown kind "${kindPlural}" in target. Use skills, commands, or agents`);
  const kind = { skills: "skill", commands: "command", agents: "agent" }[kindPlural];
  return { pack, kind, name: parts[2] };
}

// ─── pack root resolution ───────────────────────────────────────────────────

export async function resolvePackRoot(packName, sourceOverride, cwd = process.cwd()) {
  if (sourceOverride) {
    const direct = path.resolve(sourceOverride);
    if (await isPackRoot(direct, packName)) return direct;
    const nested = path.join(direct, "plugins", packName);
    if (await isPackRoot(nested, packName)) return nested;
    throw new ValidationError(`--source "${sourceOverride}" does not contain pack "${packName}"`);
  }
  const devRoot = await findDevRoot(cwd);
  if (devRoot) {
    const candidate = path.join(devRoot, "plugins", packName);
    if (await isPackRoot(candidate, packName)) return candidate;
  }
  const installed = await findInstalledPack(packName);
  if (installed) return installed;
  throw new ValidationError(
    `Pack "${packName}" not found. Either run from the marvin-toolkit repo, ` +
    `pass --source <path>, or install it first: /plugin install ${packName}@marvin-toolkit`
  );
}

async function isPackRoot(dir, packName) {
  try {
    const manifestPath = path.join(dir, ".claude-plugin", "plugin.json");
    const m = JSON.parse(await fs.readFile(manifestPath, "utf8"));
    return m.name === packName;
  } catch { return false; }
}

async function findDevRoot(start) {
  let dir = path.resolve(start);
  while (true) {
    const marketplace = path.join(dir, ".claude-plugin", "marketplace.json");
    try {
      const m = JSON.parse(await fs.readFile(marketplace, "utf8"));
      if (m.name === "marvin-toolkit") return dir;
    } catch { /* keep walking */ }
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

async function findInstalledPack(packName) {
  const root = path.join(os.homedir(), ".claude", "plugins");
  if (!existsSync(root)) return null;
  const queue = [{ dir: root, depth: 0 }];
  while (queue.length) {
    const { dir, depth } = queue.shift();
    let entries;
    try { entries = await fs.readdir(dir, { withFileTypes: true }); } catch { continue; }
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      const full = path.join(dir, e.name);
      if (e.name === packName && full.includes("marvin-toolkit") && await isPackRoot(full, packName)) return full;
      if (depth < 4) queue.push({ dir: full, depth: depth + 1 });
    }
  }
  return null;
}

// ─── manifest read ──────────────────────────────────────────────────────────

export async function readPackManifest(packRoot) {
  const p = path.join(packRoot, ".claude-plugin", "plugin.json");
  const data = JSON.parse(await fs.readFile(p, "utf8"));
  if (!data.name || !data.version) throw new ValidationError(`pack manifest at ${p} missing name/version`);
  return { name: data.name, version: data.version };
}

// ─── artifact enumeration (adapter-naive) ───────────────────────────────────
//
// Files carry a `relPath` (path within the artifact's destination) but NOT a
// resolved destination. Adapters fill in `toRel` later via `pathFor`.

export async function enumerateArtifacts(target, packRoot, only) {
  const { kind, name } = parseTarget(target);
  if (kind && name) {
    return [await buildSingleArtifact(packRoot, kind, name)];
  }
  const wantedKinds = only ?? ["skills", "commands", "agents"];
  const artifacts = [];
  for (const dirName of wantedKinds) {
    const kindSingular = { skills: "skill", commands: "command", agents: "agent" }[dirName];
    const dir = path.join(packRoot, dirName);
    if (!existsSync(dir)) continue;
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (kindSingular === "skill" && entry.isDirectory()) {
        artifacts.push(await buildSingleArtifact(packRoot, "skill", entry.name));
      } else if ((kindSingular === "command" || kindSingular === "agent") && entry.isFile() && entry.name.endsWith(".md")) {
        const baseName = entry.name.replace(/\.md$/, "");
        artifacts.push(await buildSingleArtifact(packRoot, kindSingular, baseName));
      }
    }
  }
  return artifacts;
}

async function buildSingleArtifact(packRoot, kind, name) {
  const dirName = KIND_DIRS[kind];
  if (kind === "skill") {
    const sourcePath = path.join(packRoot, "skills", name);
    if (!existsSync(sourcePath)) throw new ValidationError(`skills/${name} not found in pack`);
    const files = await listFilesRecursive(sourcePath);
    return {
      kind, name, sourcePath,
      files: files.map((rel) => ({
        from: path.join(sourcePath, rel),
        relPath: rel.split(path.sep).join("/"),
        isMarkdown: rel.toLowerCase().endsWith(".md"),
      })),
    };
  }
  const sourcePath = path.join(packRoot, dirName, `${name}.md`);
  if (!existsSync(sourcePath)) throw new ValidationError(`${dirName}/${name}.md not found in pack`);
  return {
    kind, name, sourcePath,
    files: [{ from: sourcePath, relPath: `${name}.md`, isMarkdown: true }],
  };
}

async function listFilesRecursive(dir, prefix = "") {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const out = [];
  for (const e of entries) {
    const rel = prefix ? path.join(prefix, e.name) : e.name;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...await listFilesRecursive(full, rel));
    else if (e.isFile()) out.push(rel);
  }
  return out.sort();
}

// ─── header injection (Claude-specific, used by claudeAdapter.render) ──────

export function injectHeader(content, packName, version, today) {
  const cleaned = replaceExistingHeader(content, packName);
  const headerLine = `${HEADER_PREFIX}${packName}@${version} ejected-at=${today} -->`;
  const fmEnd = findFrontmatterEnd(cleaned);
  if (fmEnd === -1) {
    return `${headerLine}\n\n${cleaned}`;
  }
  const before = cleaned.slice(0, fmEnd);
  const after = cleaned.slice(fmEnd);
  return `${before}\n${headerLine}\n${after}`;
}

function findFrontmatterEnd(content) {
  if (!content.startsWith("---\n") && !content.startsWith("---\r\n")) return -1;
  const firstLineEnd = content.indexOf("\n");
  const closingPattern = /\n---(?:\r?\n|$)/;
  const rest = content.slice(firstLineEnd + 1);
  const match = rest.match(closingPattern);
  if (!match) return -1;
  const closingStart = firstLineEnd + 1 + match.index;
  const closingEnd = closingStart + match[0].length;
  return closingEnd;
}

// TODO(user): pick the header-replacement strategy.
//
// PURPOSE: when re-ejecting, an old `<!-- marvin-eject: source=<pack>@... -->`
// header from a previous run must be removed BEFORE we inject the new one.
// Otherwise re-runs stack duplicate headers (acceptance criterion 1 + 2).
//
// CONSTRAINTS:
//   - Match by literal prefix `${HEADER_PREFIX}<packName>@`.
//   - Only remove headers for THIS pack — leave headers from other Marvin packs alone.
//   - Re-running must produce byte-identical output to the prior run.
//
// STRATEGY OPTIONS (5–10 lines each, you pick one):
//
//   (a) Single regex with anchors. Concise but watch for headers that happen
//       to appear inside fenced code blocks — those should NOT be touched.
//   (b) Line-by-line scan: split by \n, drop the first matching line plus the
//       blank line immediately after it, rejoin. Verbose but explicit.
//   (c) Markdown-AST pass — overkill, pulls in a dep we don't want.
//
// Default below is (b). Swap if you prefer (a).
export function replaceExistingHeader(content, packName) {
  const matchPrefix = `${HEADER_PREFIX}${packName}@`;
  const lines = content.split("\n");
  const out = [];
  let i = 0;
  while (i < lines.length) {
    if (lines[i].startsWith(matchPrefix)) {
      i++; // drop the header line
      if (i < lines.length && lines[i] === "") i++; // drop the blank line that follows it
      continue;
    }
    out.push(lines[i]);
    i++;
  }
  return out.join("\n");
}

// ─── ClaudeAdapter ──────────────────────────────────────────────────────────
//
// Wraps Claude-specific path & rendering rules. Other adapters (e.g. Codex
// in PR-3) implement the same shape; see cli/src/adapters/types.mjs for the
// JSDoc-typed interface.

export const claudeAdapter = {
  name: "claude",

  // Returns null (supported) or { reason, suggestion } (warning).
  unsupported(_artifact) { return null; },

  // Destination path RELATIVE TO PROJECT ROOT (forward slashes, posix).
  pathFor(artifact, fileRel) {
    switch (artifact.kind) {
      case "skill":   return `.claude/skills/${artifact.name}/${fileRel}`;
      case "command": return `.claude/commands/${artifact.name}.md`;
      case "agent":   return `.claude/agents/${artifact.name}.md`;
      default: throw new Error(`claudeAdapter: unknown kind "${artifact.kind}"`);
    }
  },

  // Content transformation (frontmatter-aware header injection for .md).
  render(_artifact, sourceContent, { isMarkdown, packName, packVersion, today }) {
    if (!isMarkdown) return sourceContent;
    return injectHeader(sourceContent, packName, packVersion, today);
  },

  // Project-root-relative manifest path.
  manifestPath() { return ".claude/.marvin-eject.json"; },

  manifestSchema() { return MANIFEST_SCHEMA; },

  // Optional hook called after a successful apply. Claude has no index file
  // to update; future targets (e.g. Codex) might rewrite a TOML config.
  async postWrite(_plan, _projectRoot) { /* no-op */ },
};

const MANIFEST_SCHEMA = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  required: ["version", "ejected"],
  properties: {
    version: { const: 1 },
    ejected: {
      type: "array",
      items: {
        type: "object",
        required: ["source", "sourceVersion", "ejectedAt", "artifact", "files"],
        properties: {
          source: { type: "string" },
          sourceVersion: { type: "string" },
          ejectedAt: { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" },
          artifact: { type: "string" },
          files: { type: "array", items: { type: "string" } },
        },
      },
    },
  },
};

// ─── manifest CRUD ──────────────────────────────────────────────────────────

export async function readManifest(projectRoot, adapter = claudeAdapter) {
  const p = path.join(projectRoot, adapter.manifestPath());
  if (!existsSync(p)) return { version: 1, ejected: [] };
  try {
    const data = JSON.parse(await fs.readFile(p, "utf8"));
    if (!data.ejected) return { version: 1, ejected: [] };
    return data;
  } catch { return { version: 1, ejected: [] }; }
}

export function upsertManifestEntry(manifest, entry) {
  const key = (e) => `${e.source}::${e.artifact}`;
  const k = key(entry);
  const idx = manifest.ejected.findIndex((e) => key(e) === k);
  if (idx >= 0) manifest.ejected[idx] = entry;
  else manifest.ejected.push(entry);
  manifest.ejected.sort((a, b) => key(a).localeCompare(key(b)));
  return manifest;
}

export function manifestEntryFor(artifact, packName, packVersion, today) {
  const kindPlural = KIND_DIRS[artifact.kind];
  return {
    source: packName,
    sourceVersion: packVersion,
    ejectedAt: today,
    artifact: `${kindPlural}/${artifact.name}`,
    files: artifact.files.map((f) => f.toRel),
  };
}

export async function writeManifest(projectRoot, manifest, adapter = claudeAdapter) {
  const rel = adapter.manifestPath();
  const dir = path.join(projectRoot, path.dirname(rel));
  await fs.mkdir(dir, { recursive: true });
  const p = path.join(projectRoot, rel);
  await fs.writeFile(p, JSON.stringify(manifest, null, 2) + "\n");
}

// ─── MCP hint extraction ────────────────────────────────────────────────────

export async function extractMcpHint(packRoot) {
  const p = path.join(packRoot, ".mcp.json");
  if (!existsSync(p)) return null;
  try {
    const data = JSON.parse(await fs.readFile(p, "utf8"));
    const servers = data?.mcpServers;
    if (!servers || typeof servers !== "object") return null;
    const names = Object.keys(servers);
    if (names.length === 0) return null;
    // `config` carries the raw mcpServers object so adapters' postWrite hooks
    // can render it into target-native config formats (e.g. TOML for Codex).
    return { servers: names, config: { mcpServers: servers } };
  } catch { return null; }
}

// ─── execution ──────────────────────────────────────────────────────────────

export function todayUtc() {
  const d = new Date();
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

export async function executePlan(plan, projectRoot) {
  const adapter = plan.adapter ?? claudeAdapter;
  // TODO(user): pick the atomicity strategy.
  //
  // PURPOSE: write all CopyOps for all artifacts. Acceptance criterion 4
  // requires "best-effort": on a mid-run failure, exit non-zero, write a
  // partial manifest reflecting only SUCCESSFUL copies, list failed file
  // in stderr.
  //
  // STRATEGY OPTIONS:
  //   (a) Sequential try/catch per file with an accumulator. Simplest;
  //       failures reported in order. (default below)
  //   (b) Promise.allSettled. Reports every failure but loses ordering.
  //   (c) Stage-then-flush via temp dir + atomic rename. Real atomicity,
  //       but rename-across-mounts fails on some filesystems.
  const written = [];
  const failures = [];
  for (const artifact of plan.artifacts) {
    const successFiles = [];
    for (const op of artifact.files) {
      try {
        const destAbs = path.join(projectRoot, op.toRel);
        await fs.mkdir(path.dirname(destAbs), { recursive: true });
        if (op.isMarkdown) {
          const src = await fs.readFile(op.from, "utf8");
          const out = adapter.render(artifact, src, {
            isMarkdown: true,
            packName: plan.packName,
            packVersion: plan.packVersion,
            today: plan.today,
          });
          await fs.writeFile(destAbs, out);
        } else {
          await fs.copyFile(op.from, destAbs);
        }
        successFiles.push(op.toRel);
      } catch (err) {
        failures.push({ file: op.toRel, error: err.message });
      }
    }
    if (successFiles.length > 0) {
      written.push({ artifact, files: successFiles });
    }
  }
  return { written, failures };
}

// ─── plan / report builders ─────────────────────────────────────────────────

export async function buildPlan({ target, only, source, projectRoot, cwd, adapter = claudeAdapter, today: todayOverride }) {
  const { pack: packName } = parseTarget(target);
  const packRoot = await resolvePackRoot(packName, source, cwd ?? projectRoot);
  const { version: packVersion } = await readPackManifest(packRoot);
  const artifacts = await enumerateArtifacts(target, packRoot, only);
  if (artifacts.length === 0) throw new ValidationError(`no artifacts matched target "${target}"`);
  const mcpHint = await extractMcpHint(packRoot);
  const today = todayOverride ?? todayUtc();
  const existingManifest = await readManifest(projectRoot, adapter);

  // Resolve destination paths via adapter, dropping artifacts that aren't supported.
  // pathFor() may return null to filter out an individual file (e.g. Codex skips
  // non-SKILL.md files inside skill folders).
  const supported = [];
  const skipped = [];
  for (const a of artifacts) {
    const warn = adapter.unsupported(a);
    if (warn) { skipped.push({ artifact: a, warning: warn }); continue; }
    a.files = a.files
      .map((f) => ({ ...f, toRel: adapter.pathFor(a, f.relPath) }))
      .filter((f) => f.toRel !== null);
    if (a.files.length === 0) {
      skipped.push({ artifact: a, warning: { reason: "adapter filtered out all files" } });
      continue;
    }
    supported.push(a);
  }

  const overwrites = [];
  const creates = [];
  for (const a of supported) {
    for (const op of a.files) {
      const dest = path.join(projectRoot, op.toRel);
      if (existsSync(dest)) overwrites.push(op.toRel);
      else creates.push(op.toRel);
    }
  }
  return {
    adapter,
    packName, packVersion, packRoot, today,
    artifacts: supported, skipped, mcpHint,
    creates, overwrites, existingManifest,
  };
}

export function buildDryRunReport(plan) {
  return {
    mode: "dry-run",
    target: plan.adapter.name,
    pack: plan.packName,
    version: plan.packVersion,
    artifacts: plan.artifacts.map((a) => `${KIND_DIRS[a.kind]}/${a.name}`),
    creates: plan.creates,
    overwrites: plan.overwrites,
    skipped: plan.skipped.map((s) => ({
      artifact: `${KIND_DIRS[s.artifact.kind]}/${s.artifact.name}`,
      reason: s.warning.reason,
      suggestion: s.warning.suggestion ?? null,
    })),
    mcpHint: plan.mcpHint,
  };
}

export function buildApplyReport(plan, exec) {
  return {
    mode: "apply",
    target: plan.adapter.name,
    pack: plan.packName,
    version: plan.packVersion,
    written: exec.written.map((w) => ({
      artifact: `${KIND_DIRS[w.artifact.kind]}/${w.artifact.name}`,
      files: w.files,
    })),
    failures: exec.failures,
    skipped: plan.skipped.map((s) => ({
      artifact: `${KIND_DIRS[s.artifact.kind]}/${s.artifact.name}`,
      reason: s.warning.reason,
      suggestion: s.warning.suggestion ?? null,
    })),
    mcpHint: plan.mcpHint,
  };
}

// ─── runner (used by both eject.mjs CLI wrapper and marvin CLI) ────────────

export async function run(argv, opts = {}) {
  const stdout = opts.stdout ?? process.stdout;
  const stderr = opts.stderr ?? process.stderr;
  const cwd = opts.cwd ?? process.cwd();
  const projectRoot = opts.projectRoot ?? cwd;
  const adapter = opts.adapter ?? claudeAdapter;

  let parsed;
  try { parsed = parseArgs(argv); } catch (err) { stderr.write(`error: ${err.message}\n`); return 2; }
  if (parsed.help) { stdout.write(usage()); return 0; }

  let plan;
  try {
    plan = await buildPlan({
      target: parsed.target, only: parsed.only, source: parsed.source,
      projectRoot, cwd, adapter, today: opts.today,
    });
  } catch (err) {
    if (err instanceof ValidationError) { stderr.write(`error: ${err.message}\n`); return 2; }
    throw err;
  }

  if (!parsed.apply) {
    stdout.write(JSON.stringify(buildDryRunReport(plan), null, 2) + "\n");
    return 0;
  }

  const exec = await executePlan(plan, projectRoot);

  const manifest = plan.existingManifest;
  for (const w of exec.written) {
    manifest.ejected = upsertManifestEntry(manifest, manifestEntryFor(w.artifact, plan.packName, plan.packVersion, plan.today)).ejected;
  }
  for (const w of exec.written) {
    const kindPlural = KIND_DIRS[w.artifact.kind];
    const key = `${plan.packName}::${kindPlural}/${w.artifact.name}`;
    const entry = manifest.ejected.find((e) => `${e.source}::${e.artifact}` === key);
    if (entry) entry.files = w.files;
  }
  try { await writeManifest(projectRoot, manifest, adapter); }
  catch (err) {
    stderr.write(`error: failed to write manifest: ${err.message}\n`);
    return 1;
  }
  await adapter.postWrite?.(plan, projectRoot);

  stdout.write(JSON.stringify(buildApplyReport(plan, exec), null, 2) + "\n");
  if (exec.failures.length > 0) {
    for (const f of exec.failures) stderr.write(`failed: ${f.file} (${f.error})\n`);
    return 1;
  }
  return 0;
}

export function usage() {
  return [
    "usage: node eject.mjs <target> [--only kinds] [--apply] [--source path]",
    "",
    "  <target>           <pack> | <pack>/skills/<name> | <pack>/commands/<name> | <pack>/agents/<name>",
    "  --only kinds       comma-separated subset: skills,commands,agents",
    "  --apply            execute the plan (default is dry-run)",
    "  --source path      explicit pack root (skips dev/installed resolution)",
    "  --help, -h         print this message",
    "",
  ].join("\n");
}
